flutter_icons:
  android: true
  ios: false
  image_path: "icons/colour_wheel.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
